// ⚠ 生成物：由 tools/gen_parity.py 从 life_co<seiki>‌​‌​‌​‍‌‌​​‎‌​‍‎‌‌‎‎‌​​‎‌​‎‎‌​‌​‌​‌‌‌‌‍​‌‌‎‎‌‌​‎‌​‍‌‌​‌‎‌‌‎‎​‎‌‎‌‍‌‍​‎​‎‌‍​‌​‎‍‌‌‍​‎​‎​‍‌‍‌‌re.py / space_core.py / commonsense.py
//   生成。别手改 —— 手改会被 `python tools/gen_parity.py --check` 判为过期，
//   而且下一次生成就没了。要改表就改 Python 那边，然后重新生成。

package com.dick.parity

/**
 * 对拍基准：这些期望值是**电脑端算出来的**，手机端必须算出一样的。
 *
 * 菜单是确定性抽样（种子 = 角色｜世界第几天｜哪一餐），所以两端算出同一份菜单
 * 是可以验证的；注入文本更是逐字比对 —— 差一个字都算漂。
 *
 * 组装格式（两端必须一致）：
 *   菜单一行 = 「餐名|主食|菜1,菜2|喝的|做法1,做法2」
 *   位置标签 = 「loc|地名|交通」或「ploc|地名|交通」
 */
object Goldens {

    // ---------------- 生活层 ----------------
    data class EraCase(val label: String, val worldJson: String, val roleJson: String,
                     val lifeEra: String, val csEra: String, val csKind: String)
    data class MenuCase(val label: String, val roleJson: String, val worldJson: String,
                     val cfgJson: String, val lifeDay: Int, val meals: List<String>,
                     val dishes: List<String>)
    data class LifeInjectCase(val label: String, val roles: List<String>,
                     val stamps: List<String>, val scale: Double, val nowIso: String,
                     val roleJson: String, val worldJson: String, val cfgJson: String,
                     val expect: String)

    val eraCases: List<EraCase> = listOf(
        EraCase(label = "现代都市", worldJson = "{\"name\": \"现代都市·合租\", \"description\": \"地铁与便利店都在楼下\", \"params\": {}}", roleJson = "", lifeEra = "现代", csEra = "现代", csKind = ""),
        EraCase(label = "明末江南", worldJson = "{\"name\": \"江南水乡·明末\", \"description\": \"大明万历年间的江南小镇\", \"params\": {\"era\": \"明清\"}}", roleJson = "", lifeEra = "明清", csEra = "明清", csKind = ""),
        EraCase(label = "仙侠（era=唐宋 + kind=仙侠）", worldJson = "{\"name\": \"仙侠·云梦宗\", \"description\": \"宗门立于云上\", \"params\": {\"era\": \"唐宋\", \"era_kind\": \"仙侠\"}}", roleJson = "", lifeEra = "唐宋", csEra = "唐宋", csKind = "仙侠"),
        EraCase(label = "末世（只有 kind）", worldJson = "{\"name\": \"末世·废土据点\", \"description\": \"路断了，油要省\", \"params\": {\"era_kind\": \"末世\"}}", roleJson = "", lifeEra = "现代", csEra = "现代", csKind = "末世"),
        EraCase(label = "角色卡写年代", worldJson = "", roleJson = "{\"name\": \"周素芬\", \"advanced\": {\"life\": {\"era\": \"1950s\"}}}", lifeEra = "现代", csEra = "1950s", csKind = ""),
        EraCase(label = "角色卡压过世界卡", worldJson = "{\"name\": \"江南水乡·明末\", \"description\": \"大明万历年间的江南小镇\", \"params\": {\"era\": \"明清\"}}", roleJson = "{\"name\": \"沈砚\", \"advanced\": {\"life\": {\"era\": \"民国\", \"region\": \"粤\", \"taste\": \"清淡\", \"avoid\": \"辣椒\"}, \"space\": {\"places\": [{\"name\": \"报馆\", \"minutes\": 35}], \"rooms\": [\"亭子间\"]}}}", lifeEra = "明清", csEra = "民国", csKind = ""),
        EraCase(label = "什么都没有", worldJson = "", roleJson = "", lifeEra = "现代", csEra = "现代", csKind = ""),
    )

    val menuCases: List<MenuCase> = listOf(
        MenuCase(label = "唐宋江南清淡", roleJson = "{\"name\": \"阿绫\", \"advanced\": {}}", worldJson = "{\"name\": \"江南水乡·明末\", \"description\": \"大明万历年间的江南小镇\", \"params\": {\"era\": \"明清\"}}", cfgJson = "{\"enabled\": true, \"era\": \"唐宋\", \"region\": \"江南\", \"taste\": \"清淡\", \"avoid\": \"\", \"show_meals\": true, \"max_chars\": 240, \"location\": \"家\"}", lifeDay = 739000,
                 meals = listOf("breakfast", "lunch", "dinner", "night"),
                 dishes = listOf("早饭|包子|蒸野菜团||蒸", "午饭|糙米饭|凉拌黄瓜|酸梅汤|拌", "晚饭|饺子|蛋花汤|凉水|煮", "夜宵|面条|鸡汤,煎蛋||炖,煎")),
        MenuCase(label = "史前只有火", roleJson = "{\"name\": \"阿绫\", \"advanced\": {}}", worldJson = "", cfgJson = "{\"enabled\": true, \"era\": \"史前\", \"region\": \"auto\", \"taste\": \"\", \"avoid\": \"\", \"show_meals\": true, \"max_chars\": 240, \"location\": \"家\"}", lifeDay = 738900,
                 meals = listOf("lunch", "dinner"),
                 dishes = listOf("午饭||石煮鱼汤||煮", "晚饭||烤野味|凉水|烤")),
        MenuCase(label = "川渝重口＋忌口", roleJson = "{\"name\": \"沈砚\", \"advanced\": {\"life\": {\"era\": \"民国\", \"region\": \"粤\", \"taste\": \"清淡\", \"avoid\": \"辣椒\"}, \"space\": {\"places\": [{\"name\": \"报馆\", \"minutes\": 35}], \"rooms\": [\"亭子间\"]}}}", worldJson = "{\"name\": \"现代都市·合租\", \"description\": \"地铁与便利店都在楼下\", \"params\": {}}", cfgJson = "{\"enabled\": true, \"era\": \"现代\", \"region\": \"川渝\", \"taste\": \"重口\", \"avoid\": \"香菜,海鲜\", \"show_meals\": true, \"max_chars\": 240, \"location\": \"家\"}", lifeDay = 739500,
                 meals = listOf("breakfast", "night"),
                 dishes = listOf("早饭|三明治|野菜粥||煮", "夜宵|包子|鸡汤,云吞面|啤酒|炖,煮")),
        MenuCase(label = "明清粤菜忌猪肉", roleJson = "{\"name\": \"阿绫\", \"advanced\": {}}", worldJson = "{\"name\": \"江南水乡·明末\", \"description\": \"大明万历年间的江南小镇\", \"params\": {\"era\": \"明清\"}}", cfgJson = "{\"enabled\": true, \"era\": \"明清\", \"region\": \"粤\", \"taste\": \"\", \"avoid\": \"猪肉\", \"show_meals\": true, \"max_chars\": 240, \"location\": \"家\"}", lifeDay = 739100,
                 meals = listOf("lunch"),
                 dishes = listOf("午饭|面条|清蒸鱼|茶|蒸")),
        MenuCase(label = "1950s 北方一天三顿", roleJson = "{\"name\": \"阿绫\", \"advanced\": {}}", worldJson = "", cfgJson = "{\"enabled\": true, \"era\": \"1950s\", \"region\": \"北方\", \"taste\": \"\", \"avoid\": \"\", \"show_meals\": true, \"max_chars\": 240, \"location\": \"家\"}", lifeDay = 739200,
                 meals = listOf("breakfast", "lunch", "dinner"),
                 dishes = listOf("早饭|馒头|腌菜||腌", "午饭|炸酱面|炖羊肉||炖", "晚饭|饺子|锅包肉,蛋花汤||炸,煮")),
        MenuCase(label = "嗜甜早饭", roleJson = "{\"name\": \"阿绫\", \"advanced\": {}}", worldJson = "{\"name\": \"现代都市·合租\", \"description\": \"地铁与便利店都在楼下\", \"params\": {}}", cfgJson = "{\"enabled\": true, \"era\": \"现代\", \"region\": \"auto\", \"taste\": \"嗜甜\", \"avoid\": \"\", \"show_meals\": true, \"max_chars\": 240, \"location\": \"家\"}", lifeDay = 739300,
                 meals = listOf("breakfast"),
                 dishes = listOf("早饭|米粉|豆浆油条,油条||炸,炸")),
        MenuCase(label = "角色卡盖过配置", roleJson = "{\"name\": \"沈砚\", \"advanced\": {\"life\": {\"era\": \"民国\", \"region\": \"粤\", \"taste\": \"清淡\", \"avoid\": \"辣椒\"}, \"space\": {\"places\": [{\"name\": \"报馆\", \"minutes\": 35}], \"rooms\": [\"亭子间\"]}}}", worldJson = "{\"name\": \"现代都市·合租\", \"description\": \"地铁与便利店都在楼下\", \"params\": {}}", cfgJson = "{\"enabled\": true, \"era\": \"现代\", \"region\": \"川渝\", \"taste\": \"\", \"avoid\": \"\", \"show_meals\": true, \"max_chars\": 240, \"location\": \"家\"}", lifeDay = 739400,
                 meals = listOf("dinner"),
                 dishes = listOf("晚饭|煲仔饭|鸡汤,炒青菜||炖,炒")),
        MenuCase(label = "史前夜宵（多半没得吃）", roleJson = "{\"name\": \"阿绫\", \"advanced\": {}}", worldJson = "", cfgJson = "{\"enabled\": true, \"era\": \"史前\", \"region\": \"粤\", \"taste\": \"\", \"avoid\": \"野菜,鱼,野味\", \"show_meals\": true, \"max_chars\": 240, \"location\": \"家\"}", lifeDay = 739600,
                 meals = listOf("night"),
                 dishes = listOf("夜宵|小米粥|||")),
        MenuCase(label = "仙侠（kind 不影响吃）", roleJson = "{\"name\": \"阿绫\", \"advanced\": {}}", worldJson = "{\"name\": \"仙侠·云梦宗\", \"description\": \"宗门立于云上\", \"params\": {\"era\": \"唐宋\", \"era_kind\": \"仙侠\"}}", cfgJson = "{\"enabled\": true, \"era\": \"auto\", \"region\": \"江南\", \"taste\": \"\", \"avoid\": \"\", \"show_meals\": true, \"max_chars\": 240, \"location\": \"家\"}", lifeDay = 739700,
                 meals = listOf("lunch", "night"),
                 dishes = listOf("午饭|饺子|煎蛋,腌菜||煎,腌", "夜宵|包子|鸡汤,蛋花汤||炖,煮")),
    )

    val lifeInjectCases: List<LifeInjectCase> = listOf(
        LifeInjectCase(label = "现代白天",
                       roles = listOf("user", "assistant", "user"),
                       stamps = listOf("2026-05-04T07:30:00", "2026-05-04T07:37:00", "2026-05-04T07:44:00"),
                       scale = 1.0, nowIso = "2026-05-04T08:20:00",
                       roleJson = "{\"name\": \"阿绫\", \"advanced\": {}}", worldJson = "{\"name\": \"现代都市·合租\", \"description\": \"地铁与便利店都在楼下\", \"params\": {}}", cfgJson = "{\"enabled\": true, \"era\": \"auto\", \"region\": \"auto\", \"taste\": \"\", \"avoid\": \"\", \"show_meals\": true, \"max_chars\": 240, \"location\": \"家\"}",
                       expect = "【生活·那边】第 1 天 08:20（清晨）\n今天： 早饭 三明治 + 兰州牛肉面 + 煎蛋，凉水。手边家伙：不粘锅、空气炸锅、电压力锅、电磁炉、烤箱、微波炉。在家。\n（生活细节自然带出即可，不必每轮都提吃的；饿了/累了在语气里体现，不要报数值。）"),
        LifeInjectCase(label = "720× 隔世",
                       roles = listOf("user", "assistant"),
                       stamps = listOf("2026-05-04T07:30:00", "2026-05-04T07:37:00"),
                       scale = 720.0, nowIso = "2026-05-04T07:33:00",
                       roleJson = "{\"name\": \"阿绫\", \"advanced\": {}}", worldJson = "{\"name\": \"江南水乡·明末\", \"description\": \"大明万历年间的江南小镇\", \"params\": {\"era\": \"明清\"}}", cfgJson = "{\"enabled\": true, \"era\": \"auto\", \"region\": \"auto\", \"taste\": \"\", \"avoid\": \"\", \"show_meals\": true, \"max_chars\": 240, \"location\": \"家\"}",
                       expect = "【生活·那边】19:30（夜里）\n今天： 早饭 包子 + 煮豆羹 + 腌菜，茶｜午饭 炸酱面 + 野菜粥｜晚饭 饺子 + 蒜蓉菠菜 + 羊肉汤，凉水。手边家伙：柴火灶、铁炒锅、蒸屉、砂锅、擀面杖、石磨。在家。\n（生活细节自然带出即可，不必每轮都提吃的；饿了/累了在语气里体现，不要报数值。）"),
        LifeInjectCase(label = "深夜",
                       roles = listOf("user"),
                       stamps = listOf("2026-05-04T02:10:00"),
                       scale = 1.0, nowIso = "2026-05-04T02:40:00",
                       roleJson = "{\"name\": \"阿绫\", \"advanced\": {}}", worldJson = "{\"name\": \"现代都市·合租\", \"description\": \"地铁与便利店都在楼下\", \"params\": {}}", cfgJson = "{\"enabled\": true, \"era\": \"auto\", \"region\": \"auto\", \"taste\": \"\", \"avoid\": \"\", \"show_meals\": true, \"max_chars\": 240, \"location\": \"家\"}",
                       expect = "【生活·那边】第 1 天 02:40（深夜）｜夜已深，她该睡了（若还醒着，给个合理的由头）\n手边家伙：不粘锅、空气炸锅、电压力锅、电磁炉、烤箱、微波炉在家。\n（生活细节自然带出即可，不必每轮都提吃的；饿了/累了在语气里体现，不要报数值。）"),
        LifeInjectCase(label = "不开菜单",
                       roles = listOf("user", "assistant"),
                       stamps = listOf("2026-05-04T07:30:00", "2026-05-04T07:37:00"),
                       scale = 1.0, nowIso = "2026-05-04T08:10:00",
                       roleJson = "{\"name\": \"阿绫\", \"advanced\": {}}", worldJson = "{\"name\": \"现代都市·合租\", \"description\": \"地铁与便利店都在楼下\", \"params\": {}}", cfgJson = "{\"enabled\": true, \"era\": \"auto\", \"region\": \"auto\", \"taste\": \"\", \"avoid\": \"\", \"show_meals\": false, \"max_chars\": 240, \"location\": \"家\"}",
                       expect = "【生活·那边】第 1 天 08:10（清晨）\n手边家伙：不粘锅、空气炸锅、电压力锅、电磁炉、烤箱、微波炉在家。\n（生活细节自然带出即可，不必每轮都提吃的；饿了/累了在语气里体现，不要报数值。）"),
        LifeInjectCase(label = "关掉生活层",
                       roles = listOf("user"),
                       stamps = listOf("2026-05-04T07:30:00"),
                       scale = 1.0, nowIso = "2026-05-04T07:30:00",
                       roleJson = "{\"name\": \"阿绫\", \"advanced\": {}}", worldJson = "{\"name\": \"现代都市·合租\", \"description\": \"地铁与便利店都在楼下\", \"params\": {}}", cfgJson = "{\"enabled\": false, \"era\": \"auto\", \"region\": \"auto\", \"taste\": \"\", \"avoid\": \"\", \"show_meals\": true, \"max_chars\": 240, \"location\": \"家\"}",
                       expect = ""),
        LifeInjectCase(label = "没有时间戳",
                       roles = listOf("system", "system"),
                       stamps = listOf("2026-05-04T07:30:00", "2026-05-04T07:37:00"),
                       scale = 1.0, nowIso = "2026-05-04T07:30:00",
                       roleJson = "{\"name\": \"阿绫\", \"advanced\": {}}", worldJson = "{\"name\": \"现代都市·合租\", \"description\": \"地铁与便利店都在楼下\", \"params\": {}}", cfgJson = "{\"enabled\": true, \"era\": \"auto\", \"region\": \"auto\", \"taste\": \"\", \"avoid\": \"\", \"show_meals\": true, \"max_chars\": 240, \"location\": \"家\"}",
                       expect = ""),
        LifeInjectCase(label = "忌口与口味",
                       roles = listOf("user"),
                       stamps = listOf("2026-05-04T07:30:00"),
                       scale = 1.0, nowIso = "2026-05-04T07:50:00",
                       roleJson = "{\"name\": \"沈砚\", \"advanced\": {\"life\": {\"era\": \"民国\", \"region\": \"粤\", \"taste\": \"清淡\", \"avoid\": \"辣椒\"}, \"space\": {\"places\": [{\"name\": \"报馆\", \"minutes\": 35}], \"rooms\": [\"亭子间\"]}}}", worldJson = "{\"name\": \"现代都市·合租\", \"description\": \"地铁与便利店都在楼下\", \"params\": {}}", cfgJson = "{\"enabled\": true, \"era\": \"auto\", \"region\": \"川渝\", \"taste\": \"重口\", \"avoid\": \"香菜,海鲜\", \"show_meals\": true, \"max_chars\": 240, \"location\": \"家\"}",
                       expect = "【生活·那边】第 1 天 07:50（清晨）\n今天： 早饭 小米粥 + 油条 + 西红柿鸡蛋面。不吃辣椒。手边家伙：煤球炉、铁炒锅、铝锅、搪瓷盆、铁勺、菜刀。口味清淡。在家。\n（生活细节自然带出即可，不必每轮都提吃的；饿了/累了在语气里体现，不要报数值。）"),
        LifeInjectCase(label = "预算很小",
                       roles = listOf("user"),
                       stamps = listOf("2026-05-04T07:30:00"),
                       scale = 1.0, nowIso = "2026-05-04T07:50:00",
                       roleJson = "{\"name\": \"阿绫\", \"advanced\": {}}", worldJson = "{\"name\": \"现代都市·合租\", \"description\": \"地铁与便利店都在楼下\", \"params\": {}}", cfgJson = "{\"enabled\": true, \"era\": \"auto\", \"region\": \"auto\", \"taste\": \"\", \"avoid\": \"\", \"show_meals\": true, \"max_chars\": 120, \"location\": \"家\"}",
                       expect = "【生活·那边】第 1 天 07:50（清晨）\n今天： 早饭 三明治 + 兰州牛肉面 + 煎蛋，凉水。手边家伙：不粘锅、空气炸锅、电压力锅、电磁炉、烤箱、微波炉。在家。\n（生活细节自然带出即可，不必每轮都提吃的；饿了/累了在语气里体现，不要报数值。）"),
        LifeInjectCase(label = "第 2 天也报天数",
                       roles = listOf("user"),
                       stamps = listOf("2026-05-04T07:30:00"),
                       scale = 1.0, nowIso = "2026-05-05T03:30:00",
                       roleJson = "{\"name\": \"阿绫\", \"advanced\": {}}", worldJson = "{\"name\": \"现代都市·合租\", \"description\": \"地铁与便利店都在楼下\", \"params\": {}}", cfgJson = "{\"enabled\": true, \"era\": \"auto\", \"region\": \"auto\", \"taste\": \"\", \"avoid\": \"\", \"show_meals\": true, \"max_chars\": 240, \"location\": \"家\"}",
                       expect = "【生活·那边】第 1 天 03:30（深夜）｜夜已深，她该睡了（若还醒着，给个合理的由头）\n手边家伙：不粘锅、空气炸锅、电压力锅、电磁炉、烤箱、微波炉在家。\n（生活细节自然带出即可，不必每轮都提吃的；饿了/累了在语气里体现，不要报数值。）"),
    )

    val lifeDescribeCases: List<LifeInjectCase> = listOf(
        LifeInjectCase(label = "现代白天",
                       roles = listOf("user", "assistant"),
                       stamps = listOf("2026-05-04T08:00:00", "2026-05-04T08:07:00"),
                       scale = 1.0, nowIso = "2026-05-04T08:40:00",
                       roleJson = "{\"name\": \"阿绫\", \"advanced\": {}}", worldJson = "{\"name\": \"现代都市·合租\", \"description\": \"地铁与便利店都在楼下\", \"params\": {}}", cfgJson = "{\"enabled\": true, \"era\": \"auto\", \"region\": \"江南\", \"taste\": \"清淡\", \"avoid\": \"香菜\", \"show_meals\": true, \"max_chars\": 240, \"location\": \"家\"}",
                       expect = "生活层：开\n世界时钟：第 1 天 08:40（清晨）｜那边已过 0.0 天（现实 40.0 分钟 × 1 倍）\n年代：现代（来自自动认出）半成品与外卖也在这个年代里\n手边家伙：不粘锅、空气炸锅、电压力锅、电磁炉、烤箱、微波炉、料理机、洗碗机\n地域：江南（来自全局）\n口味：清淡\n忌口：香菜\n今天吃过：\n  早饭：三明治 + 皮蛋 + 咸鸭蛋｜凉水"),
        LifeInjectCase(label = "仙侠（物质口径唐宋）",
                       roles = listOf("user"),
                       stamps = listOf("2026-05-04T08:00:00"),
                       scale = 1.0, nowIso = "2026-05-04T08:15:00",
                       roleJson = "{\"name\": \"阿绫\", \"advanced\": {}}", worldJson = "{\"name\": \"仙侠·云梦宗\", \"description\": \"宗门立于云上\", \"params\": {\"era\": \"唐宋\", \"era_kind\": \"仙侠\"}}", cfgJson = "{\"enabled\": true, \"era\": \"auto\", \"region\": \"auto\", \"taste\": \"\", \"avoid\": \"\", \"show_meals\": true, \"max_chars\": 240, \"location\": \"家\"}",
                       expect = "生活层：开\n世界时钟：第 1 天 08:15（清晨）｜那边已过 0.0 天（现实 15.0 分钟 × 1 倍）\n年代：唐宋（来自自动认出）薄铁锅普及 → 炒菜从此成为主流（这是中国菜的分水岭）\n手边家伙：铁炒锅、蒸笼、瓷碗、炭炉、风箱、菜刀、砧板、灶台\n今天吃过：\n  早饭：米粉 + 蒸野菜团 + 腌菜"),
        LifeInjectCase(label = "没有时间戳",
                       roles = listOf("system", "system"),
                       stamps = listOf("2026-05-04T08:00:00", "2026-05-04T08:07:00"),
                       scale = 1.0, nowIso = "2026-05-04T08:00:00",
                       roleJson = "{\"name\": \"阿绫\", \"advanced\": {}}", worldJson = "{\"name\": \"现代都市·合租\", \"description\": \"地铁与便利店都在楼下\", \"params\": {}}", cfgJson = "{\"enabled\": true, \"era\": \"auto\", \"region\": \"auto\", \"taste\": \"\", \"avoid\": \"\", \"show_meals\": true, \"max_chars\": 240, \"location\": \"家\"}",
                       expect = "生活层：开\n世界时钟：算不出（这条链里没有节点时间戳 —— 新开一局、还没说过话就会这样）\n年代：现代（来自自动认出）半成品与外卖也在这个年代里\n手边家伙：不粘锅、空气炸锅、电压力锅、电磁炉、烤箱、微波炉、料理机、洗碗机"),
        LifeInjectCase(label = "关掉生活层",
                       roles = listOf("user"),
                       stamps = listOf("2026-05-04T08:00:00"),
                       scale = 1.0, nowIso = "2026-05-04T08:00:00",
                       roleJson = "{\"name\": \"阿绫\", \"advanced\": {}}", worldJson = "{\"name\": \"现代都市·合租\", \"description\": \"地铁与便利店都在楼下\", \"params\": {}}", cfgJson = "{\"enabled\": false, \"era\": \"auto\", \"region\": \"auto\", \"taste\": \"\", \"avoid\": \"\", \"show_meals\": true, \"max_chars\": 240, \"location\": \"家\"}",
                       expect = "生活层：关\n世界时钟：第 1 天 08:00（清晨）｜那边已过 0.0 天（现实 0.0 分钟 × 1 倍）\n年代：现代（来自自动认出）半成品与外卖也在这个年代里\n手边家伙：不粘锅、空气炸锅、电压力锅、电磁炉、烤箱、微波炉、料理机、洗碗机\n今天吃过：\n  早饭：三明治 + 兰州牛肉面 + 煎蛋｜凉水"),
        LifeInjectCase(label = "刚天亮还没到饭点",
                       roles = listOf("user"),
                       stamps = listOf("2026-05-04T04:30:00"),
                       scale = 1.0, nowIso = "2026-05-04T04:40:00",
                       roleJson = "{\"name\": \"阿绫\", \"advanced\": {}}", worldJson = "{\"name\": \"现代都市·合租\", \"description\": \"地铁与便利店都在楼下\", \"params\": {}}", cfgJson = "{\"enabled\": true, \"era\": \"auto\", \"region\": \"auto\", \"taste\": \"\", \"avoid\": \"\", \"show_meals\": true, \"max_chars\": 240, \"location\": \"家\"}",
                       expect = "生活层：开\n世界时钟：第 1 天 04:40（清晨）｜那边已过 0.0 天（现实 10.0 分钟 × 1 倍）\n年代：现代（来自自动认出）半成品与外卖也在这个年代里\n手边家伙：不粘锅、空气炸锅、电压力锅、电磁炉、烤箱、微波炉、料理机、洗碗机\n今天还没吃饭点（那边刚天亮）"),
        LifeInjectCase(label = "720× 一天之内",
                       roles = listOf("user"),
                       stamps = listOf("2026-05-04T08:00:00"),
                       scale = 720.0, nowIso = "2026-05-04T08:02:00",
                       roleJson = "{\"name\": \"阿绫\", \"advanced\": {}}", worldJson = "{\"name\": \"江南水乡·明末\", \"description\": \"大明万历年间的江南小镇\", \"params\": {\"era\": \"明清\"}}", cfgJson = "{\"enabled\": true, \"era\": \"auto\", \"region\": \"auto\", \"taste\": \"\", \"avoid\": \"\", \"show_meals\": true, \"max_chars\": 240, \"location\": \"家\"}",
                       expect = "生活层：开\n世界时钟：第 2 天 08:00（清晨）｜那边已过 1.0 天（现实 2.0 分钟 × 720 倍）\n年代：明清（来自自动认出）辣椒/番茄/土豆/玉米此时才传入，之前的年代吃不到\n手边家伙：柴火灶、铁炒锅、蒸屉、砂锅、擀面杖、石磨、菜刀、砧板\n今天吃过：\n  早饭：小米粥 + 蒸野菜团 + 腌菜"),
    )

    // ---------------- 空间层 ----------------
    data class MapCase(val label: String, val worldJson: String, val roleJson: String,
                     val era: String, val home: String,
                     val places: List<Triple<String, Double, Boolean>>,
                     val rooms: List<String>, val transport: List<Pair<String, Double>>,
                     val links: List<Pair<String, Double>>)
    data class TravelCase(val label: String, val worldJson: String, val era: String,
                     val a: String, val b: String, val by: String, val expect: Double)
    data class ReachCase(val label: String, val worldJson: String, val era: String,
                     val from: String, val minutes: Double, val limit: Int, val by: String,
                     val includeRooms: Boolean, val expect: List<Pair<String, Double>>)
    data class OpenCase(val label: String, val worldJson: String, val era: String,
                     val place: String, val hour: Int, val minute: Int,
                     val ok: Boolean, val why: String)
    data class TagCase(val label: String, val text: String, val moves: List<String>,
                     val stripped: String)
    data class SpaceInjectCase(val label: String, val roleName: String, val worldJson: String,
                     val stateJson: String, val roles: List<String>, val stamps: List<String>,
                     val scale: Double, val nowIso: String, val cfgJson: String,
                     val expect: String)

    val mapCases: List<MapCase> = listOf(
        MapCase(label = "现代默认", worldJson = "", roleJson = "", era = "", home = "家",
                places = listOf(Triple("书房", 0.5, true), Triple("便利店", 6.0, false), Triple("公交站", 8.0, false), Triple("公司", 35.0, false), Triple("公园", 15.0, false), Triple("医院", 20.0, false), Triple("卧室", 0.5, true), Triple("卫生间", 0.5, true), Triple("厨房", 0.5, true), Triple("咖啡馆", 18.0, false), Triple("学校", 25.0, false), Triple("客厅", 0.5, true), Triple("家", 0.0, false), Triple("小区门口", 3.0, false), Triple("朋友家", 25.0, false), Triple("楼下", 2.0, false), Triple("火车站", 40.0, false), Triple("玄关", 0.5, true), Triple("电影院", 30.0, false), Triple("菜市场", 10.0, false), Triple("超市", 12.0, false), Triple("远方（省外）", 600.0, false), Triple("邻近城市", 180.0, false), Triple("阳台", 0.5, true), Triple("餐厅", 15.0, false)),
                rooms = listOf("卧室", "客厅", "厨房", "卫生间", "阳台", "书房", "玄关"), transport = listOf("飞机" to 0.05, "高铁" to 0.06, "开车" to 0.3, "打车" to 0.35, "骑车" to 0.4, "地铁" to 0.45, "公交" to 0.5, "步行" to 1.0, "走路" to 1.0), links = emptyList()),
        MapCase(label = "唐宋", worldJson = "{\"name\": \"江南水乡·明末\", \"description\": \"大明万历年间的江南小镇\", \"params\": {\"era\": \"明清\"}}", roleJson = "", era = "", home = "家",
                places = listOf(Triple("书房", 0.5, true), Triple("书院", 35.0, false), Triple("厢房", 0.5, true), Triple("县衙", 30.0, false), Triple("堂屋", 0.5, true), Triple("家", 0.0, false), Triple("巷口", 3.0, false), Triple("庙会", 35.0, false), Triple("府城", 360.0, false), Triple("当铺", 25.0, false), Triple("柴房", 0.5, true), Triple("正房", 0.5, true), Triple("灶房", 0.5, true), Triple("码头", 40.0, false), Triple("绣楼", 0.5, true), Triple("自家宅院", 0.0, false), Triple("茶馆", 12.0, false), Triple("院子", 0.5, true), Triple("集市", 20.0, false)),
                rooms = listOf("正房", "厢房", "灶房", "堂屋", "院子", "书房", "柴房", "绣楼"), transport = listOf("骑马" to 0.25, "马车" to 0.35, "渡船" to 0.4, "轿子" to 0.45, "快走" to 0.75, "步行" to 1.0, "走路" to 1.0), links = emptyList()),
        MapCase(label = "仙侠地图", worldJson = "{\"name\": \"仙侠·云梦宗\", \"description\": \"宗门立于云上\", \"params\": {\"era\": \"唐宋\", \"era_kind\": \"仙侠\"}}", roleJson = "", era = "", home = "家",
                places = listOf(Triple("丹房", 0.5, true), Triple("卧房", 0.5, true), Triple("坊市", 60.0, false), Triple("宗门大殿", 30.0, false), Triple("家", 0.0, false), Triple("山门", 15.0, false), Triple("洞府", 0.0, false), Triple("灵田", 0.5, true), Triple("秘境入口", 180.0, false), Triple("练功场", 10.0, false), Triple("膳堂", 8.0, false), Triple("藏经阁", 25.0, false), Triple("院子", 0.5, true), Triple("静室", 0.5, true)),
                rooms = listOf("静室", "丹房", "卧房", "院子", "灵田"), transport = listOf("传送阵" to 0.05, "御剑" to 0.08, "轻功" to 0.4, "步行" to 1.0, "走路" to 1.0), links = emptyList()),
        MapCase(label = "末世地图", worldJson = "{\"name\": \"末世·废土据点\", \"description\": \"路断了，油要省\", \"params\": {\"era_kind\": \"末世\"}}", roleJson = "", era = "", home = "家",
                places = listOf(Triple("别的据点", 300.0, false), Triple("加油站", 45.0, false), Triple("家", 0.0, false), Triple("库房", 0.5, true), Triple("据点", 0.0, false), Triple("楼下废墟", 5.0, false), Triple("灶间", 0.5, true), Triple("睡铺", 0.5, true), Triple("瞭望位", 0.5, true), Triple("补给点", 30.0, false), Triple("辐射区", 200.0, false), Triple("避难所", 120.0, false)),
                rooms = listOf("睡铺", "库房", "灶间", "瞭望位"), transport = listOf("改装车" to 0.25, "自行车" to 0.4, "小跑" to 0.7, "步行" to 1.0, "走路" to 1.0), links = emptyList()),
        MapCase(label = "世界卡自带地图", worldJson = "{\"name\": \"校园日常\", \"description\": \"六月，栀子花开\", \"params\": {\"space\": \"{\\\"places\\\": [{\\\"name\\\": \\\"教学楼\\\", \\\"minutes\\\": 6}, {\\\"name\\\": \\\"食堂\\\", \\\"minutes\\\": 8, \\\"open\\\": [6, 20]}, {\\\"name\\\": \\\"图书馆\\\", \\\"minutes\\\": 10, \\\"open\\\": [8, 22]}, {\\\"name\\\": \\\"便利店\\\", \\\"minutes\\\": 5, \\\"open\\\": [22, 2]}], \\\"home\\\": \\\"宿舍\\\", \\\"rooms\\\": [\\\"卧室\\\", \\\"阳台\\\"], \\\"transport\\\": {\\\"走路\\\": 1.0, \\\"骑车\\\": 0.4}, \\\"links\\\": {\\\"教学楼|图书馆\\\": 3}}\"}}", roleJson = "", era = "", home = "宿舍",
                places = listOf(Triple("便利店", 5.0, false), Triple("卧室", 0.5, true), Triple("图书馆", 10.0, false), Triple("宿舍", 0.0, false), Triple("教学楼", 6.0, false), Triple("阳台", 0.5, true), Triple("食堂", 8.0, false)),
                rooms = listOf("卧室", "阳台"), transport = listOf("骑车" to 0.4, "步行" to 1.0, "走路" to 1.0), links = listOf("教学楼|图书馆" to 3.0)),
        MapCase(label = "世界卡 merge", worldJson = "{\"name\": \"现代都市·加班版\", \"params\": {\"space\": \"{\\\"merge\\\": true, \\\"places\\\": [{\\\"name\\\": \\\"公司\\\", \\\"minutes\\\": 35}, {\\\"name\\\": \\\"夜宵摊\\\", \\\"minutes\\\": 9}], \\\"rooms\\\": [\\\"卧室\\\", \\\"客厅\\\", \\\"厨房\\\"]}\"}}", roleJson = "", era = "", home = "家",
                places = listOf(Triple("便利店", 6.0, false), Triple("公交站", 8.0, false), Triple("公司", 35.0, false), Triple("公园", 15.0, false), Triple("医院", 20.0, false), Triple("卧室", 0.5, true), Triple("厨房", 0.5, true), Triple("咖啡馆", 18.0, false), Triple("夜宵摊", 9.0, false), Triple("学校", 25.0, false), Triple("客厅", 0.5, true), Triple("家", 0.0, false), Triple("小区门口", 3.0, false), Triple("朋友家", 25.0, false), Triple("楼下", 2.0, false), Triple("火车站", 40.0, false), Triple("电影院", 30.0, false), Triple("菜市场", 10.0, false), Triple("超市", 12.0, false), Triple("远方（省外）", 600.0, false), Triple("邻近城市", 180.0, false), Triple("餐厅", 15.0, false)),
                rooms = listOf("卧室", "客厅", "厨房"), transport = listOf("飞机" to 0.05, "高铁" to 0.06, "开车" to 0.3, "打车" to 0.35, "骑车" to 0.4, "地铁" to 0.45, "公交" to 0.5, "步行" to 1.0, "走路" to 1.0), links = emptyList()),
        MapCase(label = "地图直接写 dict", worldJson = "{\"name\": \"地图直接写在 params 里\", \"params\": {\"space\": {\"places\": [{\"name\": \"码头\", \"minutes\": 45}], \"home\": \"船屋\"}}}", roleJson = "", era = "", home = "船屋",
                places = listOf(Triple("书房", 0.5, true), Triple("卧室", 0.5, true), Triple("卫生间", 0.5, true), Triple("厨房", 0.5, true), Triple("客厅", 0.5, true), Triple("玄关", 0.5, true), Triple("码头", 45.0, false), Triple("船屋", 0.0, false), Triple("阳台", 0.5, true)),
                rooms = listOf("卧室", "客厅", "厨房", "卫生间", "阳台", "书房", "玄关"), transport = listOf("飞机" to 0.05, "高铁" to 0.06, "开车" to 0.3, "打车" to 0.35, "骑车" to 0.4, "地铁" to 0.45, "公交" to 0.5, "步行" to 1.0, "走路" to 1.0), links = emptyList()),
        MapCase(label = "角色卡加地点", worldJson = "{\"name\": \"现代都市·合租\", \"description\": \"地铁与便利店都在楼下\", \"params\": {}}", roleJson = "{\"name\": \"沈砚\", \"advanced\": {\"life\": {\"era\": \"民国\", \"region\": \"粤\", \"taste\": \"清淡\", \"avoid\": \"辣椒\"}, \"space\": {\"places\": [{\"name\": \"报馆\", \"minutes\": 35}], \"rooms\": [\"亭子间\"]}}}", era = "", home = "家",
                places = listOf(Triple("亭子间", 0.5, true), Triple("家", 0.0, false), Triple("弄堂口", 2.0, false), Triple("报馆", 35.0, false), Triple("教堂", 30.0, false), Triple("电影院", 30.0, false), Triple("省城", 300.0, false), Triple("码头", 45.0, false), Triple("老虎灶", 6.0, false), Triple("自家住处", 0.0, false), Triple("街市", 15.0, false), Triple("警察局", 30.0, false)),
                rooms = listOf("亭子间"), transport = listOf("火车" to 0.15, "电车" to 0.2, "汽车" to 0.25, "黄包车" to 0.3, "渡船" to 0.4, "步行" to 1.0, "走路" to 1.0), links = emptyList()),
        MapCase(label = "角色卡定年代", worldJson = "", roleJson = "{\"name\": \"周素芬\", \"advanced\": {\"life\": {\"era\": \"1950s\"}}}", era = "", home = "家",
                places = listOf(Triple("供销社", 12.0, false), Triple("储藏间", 0.5, true), Triple("公社", 40.0, false), Triple("卫生所", 25.0, false), Triple("厨房", 0.5, true), Triple("县城", 200.0, false), Triple("外屋", 0.5, true), Triple("大食堂", 8.0, false), Triple("家", 0.0, false), Triple("粮站", 20.0, false), Triple("自家", 0.0, false), Triple("邮电局", 25.0, false), Triple("里屋", 0.5, true), Triple("院子", 0.5, true), Triple("院门口", 2.0, false)),
                rooms = listOf("里屋", "外屋", "厨房", "院子", "储藏间"), transport = listOf("火车" to 0.15, "自行车" to 0.35, "公共汽车" to 0.4, "步行" to 1.0, "走路" to 1.0), links = emptyList()),
        MapCase(label = "显式指定年代", worldJson = "", roleJson = "", era = "明清", home = "家",
                places = listOf(Triple("书房", 0.5, true), Triple("书院", 35.0, false), Triple("厢房", 0.5, true), Triple("县衙", 30.0, false), Triple("堂屋", 0.5, true), Triple("家", 0.0, false), Triple("巷口", 3.0, false), Triple("庙会", 35.0, false), Triple("府城", 360.0, false), Triple("当铺", 25.0, false), Triple("柴房", 0.5, true), Triple("正房", 0.5, true), Triple("灶房", 0.5, true), Triple("码头", 40.0, false), Triple("绣楼", 0.5, true), Triple("自家宅院", 0.0, false), Triple("茶馆", 12.0, false), Triple("院子", 0.5, true), Triple("集市", 20.0, false)),
                rooms = listOf("正房", "厢房", "灶房", "堂屋", "院子", "书房", "柴房", "绣楼"), transport = listOf("骑马" to 0.25, "马车" to 0.35, "渡船" to 0.4, "轿子" to 0.45, "快走" to 0.75, "步行" to 1.0, "走路" to 1.0), links = emptyList()),
    )

    val travelCases: List<TravelCase> = listOf(
        TravelCase(label = "家 → 便利店（走路）", worldJson = "", era = "", a = "家", b = "便利店", by = "", expect = 6.0),
        TravelCase(label = "家 → 便利店（骑车）", worldJson = "", era = "", a = "家", b = "便利店", by = "骑车", expect = 2.4000000000000004),
        TravelCase(label = "两个非家地点（相加）", worldJson = "", era = "", a = "便利店", b = "超市", by = "", expect = 18.0),
        TravelCase(label = "学校 → 医院（相加）", worldJson = "", era = "", a = "学校", b = "医院", by = "", expect = 45.0),
        TravelCase(label = "原地不动", worldJson = "", era = "", a = "超市", b = "超市", by = "", expect = 0.0),
        TravelCase(label = "地图上没有的名字", worldJson = "", era = "", a = "家", b = "月球", by = "", expect = 0.0),
        TravelCase(label = "links 精确覆盖", worldJson = "{\"name\": \"校园日常\", \"description\": \"六月，栀子花开\", \"params\": {\"space\": \"{\\\"places\\\": [{\\\"name\\\": \\\"教学楼\\\", \\\"minutes\\\": 6}, {\\\"name\\\": \\\"食堂\\\", \\\"minutes\\\": 8, \\\"open\\\": [6, 20]}, {\\\"name\\\": \\\"图书馆\\\", \\\"minutes\\\": 10, \\\"open\\\": [8, 22]}, {\\\"name\\\": \\\"便利店\\\", \\\"minutes\\\": 5, \\\"open\\\": [22, 2]}], \\\"home\\\": \\\"宿舍\\\", \\\"rooms\\\": [\\\"卧室\\\", \\\"阳台\\\"], \\\"transport\\\": {\\\"走路\\\": 1.0, \\\"骑车\\\": 0.4}, \\\"links\\\": {\\\"教学楼|图书馆\\\": 3}}\"}}", era = "", a = "教学楼", b = "图书馆", by = "", expect = 3.0),
        TravelCase(label = "links 反向也算", worldJson = "{\"name\": \"校园日常\", \"description\": \"六月，栀子花开\", \"params\": {\"space\": \"{\\\"places\\\": [{\\\"name\\\": \\\"教学楼\\\", \\\"minutes\\\": 6}, {\\\"name\\\": \\\"食堂\\\", \\\"minutes\\\": 8, \\\"open\\\": [6, 20]}, {\\\"name\\\": \\\"图书馆\\\", \\\"minutes\\\": 10, \\\"open\\\": [8, 22]}, {\\\"name\\\": \\\"便利店\\\", \\\"minutes\\\": 5, \\\"open\\\": [22, 2]}], \\\"home\\\": \\\"宿舍\\\", \\\"rooms\\\": [\\\"卧室\\\", \\\"阳台\\\"], \\\"transport\\\": {\\\"走路\\\": 1.0, \\\"骑车\\\": 0.4}, \\\"links\\\": {\\\"教学楼|图书馆\\\": 3}}\"}}", era = "", a = "图书馆", b = "教学楼", by = "骑车", expect = 1.2000000000000002),
        TravelCase(label = "宿舍 → 便利店", worldJson = "{\"name\": \"校园日常\", \"description\": \"六月，栀子花开\", \"params\": {\"space\": \"{\\\"places\\\": [{\\\"name\\\": \\\"教学楼\\\", \\\"minutes\\\": 6}, {\\\"name\\\": \\\"食堂\\\", \\\"minutes\\\": 8, \\\"open\\\": [6, 20]}, {\\\"name\\\": \\\"图书馆\\\", \\\"minutes\\\": 10, \\\"open\\\": [8, 22]}, {\\\"name\\\": \\\"便利店\\\", \\\"minutes\\\": 5, \\\"open\\\": [22, 2]}], \\\"home\\\": \\\"宿舍\\\", \\\"rooms\\\": [\\\"卧室\\\", \\\"阳台\\\"], \\\"transport\\\": {\\\"走路\\\": 1.0, \\\"骑车\\\": 0.4}, \\\"links\\\": {\\\"教学楼|图书馆\\\": 3}}\"}}", era = "", a = "宿舍", b = "便利店", by = "", expect = 5.0),
        TravelCase(label = "唐宋没有地铁（退回通用系数）", worldJson = "{\"name\": \"江南水乡·明末\", \"description\": \"大明万历年间的江南小镇\", \"params\": {\"era\": \"明清\"}}", era = "", a = "自家宅院", b = "茶肆", by = "地铁", expect = 0.0),
        TravelCase(label = "唐宋坐轿子", worldJson = "{\"name\": \"江南水乡·明末\", \"description\": \"大明万历年间的江南小镇\", \"params\": {\"era\": \"明清\"}}", era = "", a = "自家宅院", b = "码头", by = "轿子", expect = 18.0),
    )

    val reachCases: List<ReachCase> = listOf(
        ReachCase(label = "现代 20 分钟", worldJson = "", era = "", from = "家", minutes = 20.0, limit = 4, by = "", includeRooms = false,
                 expect = listOf("楼下" to 2.0, "小区门口" to 3.0, "便利店" to 6.0, "公交站" to 8.0)),
        ReachCase(label = "现代 5 分钟（哪都去不了）", worldJson = "", era = "", from = "家", minutes = 5.0, limit = 4, by = "", includeRooms = false,
                 expect = listOf("楼下" to 2.0, "小区门口" to 3.0)),
        ReachCase(label = "现代 600 分钟（含远方）", worldJson = "", era = "", from = "家", minutes = 600.0, limit = 20, by = "", includeRooms = false,
                 expect = listOf("楼下" to 2.0, "小区门口" to 3.0, "便利店" to 6.0, "公交站" to 8.0, "菜市场" to 10.0, "超市" to 12.0, "公园" to 15.0, "餐厅" to 15.0, "咖啡馆" to 18.0, "医院" to 20.0, "学校" to 25.0, "朋友家" to 25.0, "电影院" to 30.0, "公司" to 35.0, "火车站" to 40.0, "邻近城市" to 180.0, "远方（省外）" to 600.0)),
        ReachCase(label = "骑车更快", worldJson = "", era = "", from = "家", minutes = 40.0, limit = 6, by = "骑车", includeRooms = false,
                 expect = listOf("楼下" to 0.8, "小区门口" to 1.2000000000000002, "便利店" to 2.4000000000000004, "公交站" to 3.2, "菜市场" to 4.0, "超市" to 4.800000000000001)),
        ReachCase(label = "算上屋里", worldJson = "{\"name\": \"校园日常\", \"description\": \"六月，栀子花开\", \"params\": {\"space\": \"{\\\"places\\\": [{\\\"name\\\": \\\"教学楼\\\", \\\"minutes\\\": 6}, {\\\"name\\\": \\\"食堂\\\", \\\"minutes\\\": 8, \\\"open\\\": [6, 20]}, {\\\"name\\\": \\\"图书馆\\\", \\\"minutes\\\": 10, \\\"open\\\": [8, 22]}, {\\\"name\\\": \\\"便利店\\\", \\\"minutes\\\": 5, \\\"open\\\": [22, 2]}], \\\"home\\\": \\\"宿舍\\\", \\\"rooms\\\": [\\\"卧室\\\", \\\"阳台\\\"], \\\"transport\\\": {\\\"走路\\\": 1.0, \\\"骑车\\\": 0.4}, \\\"links\\\": {\\\"教学楼|图书馆\\\": 3}}\"}}", era = "", from = "宿舍", minutes = 1.0, limit = 6, by = "", includeRooms = true,
                 expect = listOf("卧室" to 0.5, "阳台" to 0.5)),
        ReachCase(label = "不算屋里", worldJson = "{\"name\": \"校园日常\", \"description\": \"六月，栀子花开\", \"params\": {\"space\": \"{\\\"places\\\": [{\\\"name\\\": \\\"教学楼\\\", \\\"minutes\\\": 6}, {\\\"name\\\": \\\"食堂\\\", \\\"minutes\\\": 8, \\\"open\\\": [6, 20]}, {\\\"name\\\": \\\"图书馆\\\", \\\"minutes\\\": 10, \\\"open\\\": [8, 22]}, {\\\"name\\\": \\\"便利店\\\", \\\"minutes\\\": 5, \\\"open\\\": [22, 2]}], \\\"home\\\": \\\"宿舍\\\", \\\"rooms\\\": [\\\"卧室\\\", \\\"阳台\\\"], \\\"transport\\\": {\\\"走路\\\": 1.0, \\\"骑车\\\": 0.4}, \\\"links\\\": {\\\"教学楼|图书馆\\\": 3}}\"}}", era = "", from = "宿舍", minutes = 1.0, limit = 6, by = "", includeRooms = false,
                 expect = emptyList()),
        ReachCase(label = "不限条数", worldJson = "", era = "", from = "家", minutes = 30.0, limit = 0, by = "", includeRooms = false,
                 expect = listOf("楼下" to 2.0, "小区门口" to 3.0, "便利店" to 6.0, "公交站" to 8.0, "菜市场" to 10.0, "超市" to 12.0, "公园" to 15.0, "餐厅" to 15.0, "咖啡馆" to 18.0, "医院" to 20.0, "学校" to 25.0, "朋友家" to 25.0, "电影院" to 30.0)),
    )

    val openCases: List<OpenCase> = listOf(
        OpenCase(label = "食堂 05:59 没开", worldJson = "{\"name\": \"校园日常\", \"description\": \"六月，栀子花开\", \"params\": {\"space\": \"{\\\"places\\\": [{\\\"name\\\": \\\"教学楼\\\", \\\"minutes\\\": 6}, {\\\"name\\\": \\\"食堂\\\", \\\"minutes\\\": 8, \\\"open\\\": [6, 20]}, {\\\"name\\\": \\\"图书馆\\\", \\\"minutes\\\": 10, \\\"open\\\": [8, 22]}, {\\\"name\\\": \\\"便利店\\\", \\\"minutes\\\": 5, \\\"open\\\": [22, 2]}], \\\"home\\\": \\\"宿舍\\\", \\\"rooms\\\": [\\\"卧室\\\", \\\"阳台\\\"], \\\"transport\\\": {\\\"走路\\\": 1.0, \\\"骑车\\\": 0.4}, \\\"links\\\": {\\\"教学楼|图书馆\\\": 3}}\"}}", era = "", place = "食堂", hour = 5, minute = 59, ok = false, why = "食堂 的营业时间是 06:00–20:00"),
        OpenCase(label = "食堂 06:00 开了", worldJson = "{\"name\": \"校园日常\", \"description\": \"六月，栀子花开\", \"params\": {\"space\": \"{\\\"places\\\": [{\\\"name\\\": \\\"教学楼\\\", \\\"minutes\\\": 6}, {\\\"name\\\": \\\"食堂\\\", \\\"minutes\\\": 8, \\\"open\\\": [6, 20]}, {\\\"name\\\": \\\"图书馆\\\", \\\"minutes\\\": 10, \\\"open\\\": [8, 22]}, {\\\"name\\\": \\\"便利店\\\", \\\"minutes\\\": 5, \\\"open\\\": [22, 2]}], \\\"home\\\": \\\"宿舍\\\", \\\"rooms\\\": [\\\"卧室\\\", \\\"阳台\\\"], \\\"transport\\\": {\\\"走路\\\": 1.0, \\\"骑车\\\": 0.4}, \\\"links\\\": {\\\"教学楼|图书馆\\\": 3}}\"}}", era = "", place = "食堂", hour = 6, minute = 0, ok = true, why = ""),
        OpenCase(label = "食堂 19:59 还开", worldJson = "{\"name\": \"校园日常\", \"description\": \"六月，栀子花开\", \"params\": {\"space\": \"{\\\"places\\\": [{\\\"name\\\": \\\"教学楼\\\", \\\"minutes\\\": 6}, {\\\"name\\\": \\\"食堂\\\", \\\"minutes\\\": 8, \\\"open\\\": [6, 20]}, {\\\"name\\\": \\\"图书馆\\\", \\\"minutes\\\": 10, \\\"open\\\": [8, 22]}, {\\\"name\\\": \\\"便利店\\\", \\\"minutes\\\": 5, \\\"open\\\": [22, 2]}], \\\"home\\\": \\\"宿舍\\\", \\\"rooms\\\": [\\\"卧室\\\", \\\"阳台\\\"], \\\"transport\\\": {\\\"走路\\\": 1.0, \\\"骑车\\\": 0.4}, \\\"links\\\": {\\\"教学楼|图书馆\\\": 3}}\"}}", era = "", place = "食堂", hour = 19, minute = 59, ok = true, why = ""),
        OpenCase(label = "食堂 20:00 关门", worldJson = "{\"name\": \"校园日常\", \"description\": \"六月，栀子花开\", \"params\": {\"space\": \"{\\\"places\\\": [{\\\"name\\\": \\\"教学楼\\\", \\\"minutes\\\": 6}, {\\\"name\\\": \\\"食堂\\\", \\\"minutes\\\": 8, \\\"open\\\": [6, 20]}, {\\\"name\\\": \\\"图书馆\\\", \\\"minutes\\\": 10, \\\"open\\\": [8, 22]}, {\\\"name\\\": \\\"便利店\\\", \\\"minutes\\\": 5, \\\"open\\\": [22, 2]}], \\\"home\\\": \\\"宿舍\\\", \\\"rooms\\\": [\\\"卧室\\\", \\\"阳台\\\"], \\\"transport\\\": {\\\"走路\\\": 1.0, \\\"骑车\\\": 0.4}, \\\"links\\\": {\\\"教学楼|图书馆\\\": 3}}\"}}", era = "", place = "食堂", hour = 20, minute = 0, ok = false, why = "食堂 的营业时间是 06:00–20:00"),
        OpenCase(label = "便利店 23:00 开（跨天）", worldJson = "{\"name\": \"校园日常\", \"description\": \"六月，栀子花开\", \"params\": {\"space\": \"{\\\"places\\\": [{\\\"name\\\": \\\"教学楼\\\", \\\"minutes\\\": 6}, {\\\"name\\\": \\\"食堂\\\", \\\"minutes\\\": 8, \\\"open\\\": [6, 20]}, {\\\"name\\\": \\\"图书馆\\\", \\\"minutes\\\": 10, \\\"open\\\": [8, 22]}, {\\\"name\\\": \\\"便利店\\\", \\\"minutes\\\": 5, \\\"open\\\": [22, 2]}], \\\"home\\\": \\\"宿舍\\\", \\\"rooms\\\": [\\\"卧室\\\", \\\"阳台\\\"], \\\"transport\\\": {\\\"走路\\\": 1.0, \\\"骑车\\\": 0.4}, \\\"links\\\": {\\\"教学楼|图书馆\\\": 3}}\"}}", era = "", place = "便利店", hour = 23, minute = 0, ok = true, why = ""),
        OpenCase(label = "便利店 01:30 还开（跨天）", worldJson = "{\"name\": \"校园日常\", \"description\": \"六月，栀子花开\", \"params\": {\"space\": \"{\\\"places\\\": [{\\\"name\\\": \\\"教学楼\\\", \\\"minutes\\\": 6}, {\\\"name\\\": \\\"食堂\\\", \\\"minutes\\\": 8, \\\"open\\\": [6, 20]}, {\\\"name\\\": \\\"图书馆\\\", \\\"minutes\\\": 10, \\\"open\\\": [8, 22]}, {\\\"name\\\": \\\"便利店\\\", \\\"minutes\\\": 5, \\\"open\\\": [22, 2]}], \\\"home\\\": \\\"宿舍\\\", \\\"rooms\\\": [\\\"卧室\\\", \\\"阳台\\\"], \\\"transport\\\": {\\\"走路\\\": 1.0, \\\"骑车\\\": 0.4}, \\\"links\\\": {\\\"教学楼|图书馆\\\": 3}}\"}}", era = "", place = "便利店", hour = 1, minute = 30, ok = true, why = ""),
        OpenCase(label = "便利店 03:00 关门（跨天）", worldJson = "{\"name\": \"校园日常\", \"description\": \"六月，栀子花开\", \"params\": {\"space\": \"{\\\"places\\\": [{\\\"name\\\": \\\"教学楼\\\", \\\"minutes\\\": 6}, {\\\"name\\\": \\\"食堂\\\", \\\"minutes\\\": 8, \\\"open\\\": [6, 20]}, {\\\"name\\\": \\\"图书馆\\\", \\\"minutes\\\": 10, \\\"open\\\": [8, 22]}, {\\\"name\\\": \\\"便利店\\\", \\\"minutes\\\": 5, \\\"open\\\": [22, 2]}], \\\"home\\\": \\\"宿舍\\\", \\\"rooms\\\": [\\\"卧室\\\", \\\"阳台\\\"], \\\"transport\\\": {\\\"走路\\\": 1.0, \\\"骑车\\\": 0.4}, \\\"links\\\": {\\\"教学楼|图书馆\\\": 3}}\"}}", era = "", place = "便利店", hour = 3, minute = 0, ok = false, why = "便利店 的营业时间是 22:00–02:00"),
        OpenCase(label = "图书馆没写 open 视为一直开", worldJson = "{\"name\": \"校园日常\", \"description\": \"六月，栀子花开\", \"params\": {\"space\": \"{\\\"places\\\": [{\\\"name\\\": \\\"教学楼\\\", \\\"minutes\\\": 6}, {\\\"name\\\": \\\"食堂\\\", \\\"minutes\\\": 8, \\\"open\\\": [6, 20]}, {\\\"name\\\": \\\"图书馆\\\", \\\"minutes\\\": 10, \\\"open\\\": [8, 22]}, {\\\"name\\\": \\\"便利店\\\", \\\"minutes\\\": 5, \\\"open\\\": [22, 2]}], \\\"home\\\": \\\"宿舍\\\", \\\"rooms\\\": [\\\"卧室\\\", \\\"阳台\\\"], \\\"transport\\\": {\\\"走路\\\": 1.0, \\\"骑车\\\": 0.4}, \\\"links\\\": {\\\"教学楼|图书馆\\\": 3}}\"}}", era = "", place = "教学楼", hour = 3, minute = 0, ok = true, why = ""),
    )

    val tagCases: List<TagCase> = listOf(
        TagCase(label = "她推门进来。[loc:学", text = "她推门进来。[loc:学校|骑车] 又坐下。", moves = listOf("loc|学校|骑车"), stripped = "她推门进来。 又坐下。"),
        TagCase(label = "[ploc:家/厨房] ", text = "[ploc:家/厨房] 锅里的水开了。", moves = listOf("ploc|家/厨房|"), stripped = " 锅里的水开了。"),
        TagCase(label = "先到 [loc: 图书馆", text = "先到 [loc: 图书馆 ｜ 地铁 ] 再说", moves = listOf("loc|图书馆|地铁"), stripped = "先到  再说"),
        TagCase(label = "[位置:菜市场][地点:", text = "[位置:菜市场][地点:超市]", moves = listOf("loc|菜市场|", "loc|超市|"), stripped = ""),
        TagCase(label = "[LOC:学校]", text = "[LOC:学校]", moves = listOf("loc|学校|"), stripped = ""),
        TagCase(label = "没有标签的一段话。", text = "没有标签的一段话。", moves = emptyList(), stripped = "没有标签的一段话。"),
        TagCase(label = "[loc:朝阳, 北京]", text = "[loc:朝阳, 北京]", moves = listOf("loc|朝阳, 北京|"), stripped = ""),
        TagCase(label = "[loc:家/厨房|走路", text = "[loc:家/厨房|走路] 和 [ploc:公司|打车]", moves = listOf("loc|家/厨房|走路", "ploc|公司|打车"), stripped = " 和 "),
        TagCase(label = "[loc:便利店|]", text = "[loc:便利店|]", moves = listOf("loc|便利店||"), stripped = ""),
        TagCase(label = "[loc:|骑车]", text = "[loc:|骑车]", moves = listOf("loc||骑车"), stripped = ""),
        TagCase(label = "[loc:A|B|C]", text = "[loc:A|B|C]", moves = listOf("loc|A|B|C"), stripped = ""),
        TagCase(label = "空串", text = "", moves = emptyList(), stripped = ""),
    )

    val spaceInjectCases: List<SpaceInjectCase> = listOf(
        SpaceInjectCase(label = "从没记过位置", roleName = "阿绫",
                       worldJson = "",
                       stateJson = "",
                       roles = listOf("user"), stamps = listOf("2026-05-04T12:00:00"),
                       scale = 1.0, nowIso = "2026-05-04T12:00:00",
                       cfgJson = "{\"enabled\": true, \"max_chars\": 240, \"show_reachable\": true, \"reachable_limit\": 4, \"default_transport\": \"走路\", \"warn_when_impossible\": true, \"state_dir\": \"space\"}", expect = "【空间】阿绫 现在：家\n屋里：卧室、客厅、厨房、卫生间、阳台、书房、玄关（都在 1 分钟内）\n（换地方要交代怎么去的、路上花了多久；来不及去的地方就别凭空出现 —— 可以用 [loc:地名] / [loc:地名|骑车] 标注她到了哪，[ploc:地名] 标你到哪；标注不会显示给玩家。）"),
        SpaceInjectCase(label = "在学校，骑车来的", roleName = "阿绫",
                       worldJson = "{\"name\": \"校园日常\", \"description\": \"六月，栀子花开\", \"params\": {\"space\": \"{\\\"places\\\": [{\\\"name\\\": \\\"教学楼\\\", \\\"minutes\\\": 6}, {\\\"name\\\": \\\"食堂\\\", \\\"minutes\\\": 8, \\\"open\\\": [6, 20]}, {\\\"name\\\": \\\"图书馆\\\", \\\"minutes\\\": 10, \\\"open\\\": [8, 22]}, {\\\"name\\\": \\\"便利店\\\", \\\"minutes\\\": 5, \\\"open\\\": [22, 2]}], \\\"home\\\": \\\"宿舍\\\", \\\"rooms\\\": [\\\"卧室\\\", \\\"阳台\\\"], \\\"transport\\\": {\\\"走路\\\": 1.0, \\\"骑车\\\": 0.4}, \\\"links\\\": {\\\"教学楼|图书馆\\\": 3}}\"}}",
                       stateJson = "{\"place\": \"教学楼\", \"since\": \"2026-05-04T11:40:00\", \"by\": \"骑车\", \"scale\": 1.0}",
                       roles = listOf("user", "assistant"), stamps = listOf("2026-05-04T11:53:00", "2026-05-04T12:00:00"),
                       scale = 1.0, nowIso = "2026-05-04T12:00:00",
                       cfgJson = "{\"enabled\": true, \"max_chars\": 240, \"show_reachable\": true, \"reachable_limit\": 4, \"default_transport\": \"走路\", \"warn_when_impossible\": true, \"state_dir\": \"space\"}", expect = "【空间】阿绫 现在：教学楼（20 分钟前到，骑车）\n（换地方要交代怎么去的、路上花了多久；来不及去的地方就别凭空出现 —— 可以用 [loc:地名] / [loc:地名|骑车] 标注她到了哪，[ploc:地名] 标你到哪；标注不会显示给玩家。）"),
        SpaceInjectCase(label = "在家（该报屋里）", roleName = "阿绫",
                       worldJson = "{\"name\": \"校园日常\", \"description\": \"六月，栀子花开\", \"params\": {\"space\": \"{\\\"places\\\": [{\\\"name\\\": \\\"教学楼\\\", \\\"minutes\\\": 6}, {\\\"name\\\": \\\"食堂\\\", \\\"minutes\\\": 8, \\\"open\\\": [6, 20]}, {\\\"name\\\": \\\"图书馆\\\", \\\"minutes\\\": 10, \\\"open\\\": [8, 22]}, {\\\"name\\\": \\\"便利店\\\", \\\"minutes\\\": 5, \\\"open\\\": [22, 2]}], \\\"home\\\": \\\"宿舍\\\", \\\"rooms\\\": [\\\"卧室\\\", \\\"阳台\\\"], \\\"transport\\\": {\\\"走路\\\": 1.0, \\\"骑车\\\": 0.4}, \\\"links\\\": {\\\"教学楼|图书馆\\\": 3}}\"}}",
                       stateJson = "{\"place\": \"宿舍\", \"since\": \"2026-05-04T10:50:00\", \"by\": \"走路\", \"scale\": 1.0}",
                       roles = listOf("user"), stamps = listOf("2026-05-04T12:00:00"),
                       scale = 1.0, nowIso = "2026-05-04T12:00:00",
                       cfgJson = "{\"enabled\": true, \"max_chars\": 240, \"show_reachable\": true, \"reachable_limit\": 4, \"default_transport\": \"走路\", \"warn_when_impossible\": true, \"state_dir\": \"space\"}", expect = "【空间】阿绫 现在：宿舍（70 分钟前到，走路）\n屋里：卧室、阳台（都在 1 分钟内）\n（换地方要交代怎么去的、路上花了多久；来不及去的地方就别凭空出现 —— 可以用 [loc:地名] / [loc:地名|骑车] 标注她到了哪，[ploc:地名] 标你到哪；标注不会显示给玩家。）"),
        SpaceInjectCase(label = "地图外的地方", roleName = "阿绫",
                       worldJson = "",
                       stateJson = "{\"place\": \"月球基地\", \"since\": \"2026-05-04T11:45:00\", \"offmap\": \"月球基地\", \"by\": \"走路\"}",
                       roles = listOf("user"), stamps = listOf("2026-05-04T12:00:00"),
                       scale = 1.0, nowIso = "2026-05-04T12:00:00",
                       cfgJson = "{\"enabled\": true, \"max_chars\": 240, \"show_reachable\": true, \"reachable_limit\": 4, \"default_transport\": \"走路\", \"warn_when_impossible\": true, \"state_dir\": \"space\"}", expect = "【空间】阿绫 现在：月球基地（15 分钟前到，走路）\n⚠ 月球基地 不在地图上 —— 按你说的记下了，但这地方之后要算路费就只能按邻近代估。\n这0分钟够去：家(0分)\n（换地方要交代怎么去的、路上花了多久；来不及去的地方就别凭空出现 —— 可以用 [loc:地名] / [loc:地名|骑车] 标注她到了哪，[ploc:地名] 标你到哪；标注不会显示给玩家。）"),
        SpaceInjectCase(label = "穿帮一次（要提醒）", roleName = "阿绫",
                       worldJson = "",
                       stateJson = "{\"place\": \"火车站\", \"since\": \"2026-05-04T11:59:00\", \"prev\": \"家\", \"by\": \"走路\", \"violation\": {\"from\": \"家\", \"to\": \"火车站\", \"need\": 40.0, \"have\": 1.0, \"at\": \"2026-05-04T12:00:00\", \"why\": \"从家到火车站要 40 分钟，这段时间只过了 1 分钟\"}}",
                       roles = listOf("user"), stamps = listOf("2026-05-04T12:00:00"),
                       scale = 1.0, nowIso = "2026-05-04T12:00:00",
                       cfgJson = "{\"enabled\": true, \"max_chars\": 240, \"show_reachable\": true, \"reachable_limit\": 4, \"default_transport\": \"走路\", \"warn_when_impossible\": true, \"state_dir\": \"space\"}", expect = "【空间】阿绫 现在：火车站（1 分钟前到，走路）\n⚠ 上一轮她 1 分钟前还在家，现在写到火车站：从家到火车站要 40 分钟，这段时间只过了 1 分钟 —— 要么补一句路上/交通方式，要么把她拉回原处。\n（换地方要交代怎么去的、路上花了多久；来不及去的地方就别凭空出现 —— 可以用 [loc:地名] / [loc:地名|骑车] 标注她到了哪，[ploc:地名] 标你到哪；标注不会显示给玩家。）"),
        SpaceInjectCase(label = "穿帮已提醒两次（不再念）", roleName = "阿绫",
                       worldJson = "",
                       stateJson = "{\"place\": \"火车站\", \"since\": \"2026-05-04T11:59:00\", \"by\": \"走路\", \"violation\": {\"from\": \"家\", \"to\": \"火车站\", \"need\": 40.0, \"have\": 1.0, \"at\": \"2026-05-04T12:00:00\", \"why\": \"来不及\", \"warned\": 2}}",
                       roles = listOf("user"), stamps = listOf("2026-05-04T12:00:00"),
                       scale = 1.0, nowIso = "2026-05-04T12:00:00",
                       cfgJson = "{\"enabled\": true, \"max_chars\": 240, \"show_reachable\": true, \"reachable_limit\": 4, \"default_transport\": \"走路\", \"warn_when_impossible\": true, \"state_dir\": \"space\"}", expect = "【空间】阿绫 现在：火车站（1 分钟前到，走路）\n（换地方要交代怎么去的、路上花了多久；来不及去的地方就别凭空出现 —— 可以用 [loc:地名] / [loc:地名|骑车] 标注她到了哪，[ploc:地名] 标你到哪；标注不会显示给玩家。）"),
        SpaceInjectCase(label = "玩家也在地图上", roleName = "阿绫",
                       worldJson = "{\"name\": \"校园日常\", \"description\": \"六月，栀子花开\", \"params\": {\"space\": \"{\\\"places\\\": [{\\\"name\\\": \\\"教学楼\\\", \\\"minutes\\\": 6}, {\\\"name\\\": \\\"食堂\\\", \\\"minutes\\\": 8, \\\"open\\\": [6, 20]}, {\\\"name\\\": \\\"图书馆\\\", \\\"minutes\\\": 10, \\\"open\\\": [8, 22]}, {\\\"name\\\": \\\"便利店\\\", \\\"minutes\\\": 5, \\\"open\\\": [22, 2]}], \\\"home\\\": \\\"宿舍\\\", \\\"rooms\\\": [\\\"卧室\\\", \\\"阳台\\\"], \\\"transport\\\": {\\\"走路\\\": 1.0, \\\"骑车\\\": 0.4}, \\\"links\\\": {\\\"教学楼|图书馆\\\": 3}}\"}}",
                       stateJson = "{\"place\": \"教学楼\", \"since\": \"2026-05-04T11:30:00\", \"by\": \"走路\", \"player_place\": \"便利店\", \"player_since\": \"2026-05-04T11:48:00\"}",
                       roles = listOf("user"), stamps = listOf("2026-05-04T12:00:00"),
                       scale = 1.0, nowIso = "2026-05-04T12:00:00",
                       cfgJson = "{\"enabled\": true, \"max_chars\": 240, \"show_reachable\": true, \"reachable_limit\": 4, \"default_transport\": \"走路\", \"warn_when_impossible\": true, \"state_dir\": \"space\"}", expect = "【空间】阿绫 现在：教学楼（30 分钟前到，走路）\n你在便利店，到这儿要 11 分钟\n（换地方要交代怎么去的、路上花了多久；来不及去的地方就别凭空出现 —— 可以用 [loc:地名] / [loc:地名|骑车] 标注她到了哪，[ploc:地名] 标你到哪；标注不会显示给玩家。）"),
        SpaceInjectCase(label = "营业时间对不上（凌晨的食堂）", roleName = "阿绫",
                       worldJson = "{\"name\": \"校园日常\", \"description\": \"六月，栀子花开\", \"params\": {\"space\": \"{\\\"places\\\": [{\\\"name\\\": \\\"教学楼\\\", \\\"minutes\\\": 6}, {\\\"name\\\": \\\"食堂\\\", \\\"minutes\\\": 8, \\\"open\\\": [6, 20]}, {\\\"name\\\": \\\"图书馆\\\", \\\"minutes\\\": 10, \\\"open\\\": [8, 22]}, {\\\"name\\\": \\\"便利店\\\", \\\"minutes\\\": 5, \\\"open\\\": [22, 2]}], \\\"home\\\": \\\"宿舍\\\", \\\"rooms\\\": [\\\"卧室\\\", \\\"阳台\\\"], \\\"transport\\\": {\\\"走路\\\": 1.0, \\\"骑车\\\": 0.4}, \\\"links\\\": {\\\"教学楼|图书馆\\\": 3}}\"}}",
                       stateJson = "{\"place\": \"食堂\", \"since\": \"2026-05-04T03:10:00\", \"by\": \"走路\"}",
                       roles = listOf("user"), stamps = listOf("2026-05-04T03:10:00"),
                       scale = 1.0, nowIso = "2026-05-04T03:10:00",
                       cfgJson = "{\"enabled\": true, \"max_chars\": 240, \"show_reachable\": true, \"reachable_limit\": 4, \"default_transport\": \"走路\", \"warn_when_impossible\": true, \"state_dir\": \"space\"}", expect = "【空间】阿绫 现在：食堂（0 分钟前到，走路）\n⚠ 食堂 的营业时间是 06:00–20:00 —— 这个点她不该在那儿，给个由头或换个地方。\n（换地方要交代怎么去的、路上花了多久；来不及去的地方就别凭空出现 —— 可以用 [loc:地名] / [loc:地名|骑车] 标注她到了哪，[ploc:地名] 标你到哪；标注不会显示给玩家。）"),
        SpaceInjectCase(label = "明清地图的茶肆（没写营业时间就不提醒）", roleName = "阿绫",
                       worldJson = "{\"name\": \"江南水乡·明末\", \"description\": \"大明万历年间的江南小镇\", \"params\": {\"era\": \"明清\"}}",
                       stateJson = "{\"place\": \"茶肆\", \"since\": \"2026-05-04T03:10:00\", \"by\": \"走路\"}",
                       roles = listOf("user"), stamps = listOf("2026-05-04T03:10:00"),
                       scale = 1.0, nowIso = "2026-05-04T03:10:00",
                       cfgJson = "{\"enabled\": true, \"max_chars\": 240, \"show_reachable\": true, \"reachable_limit\": 4, \"default_transport\": \"走路\", \"warn_when_impossible\": true, \"state_dir\": \"space\"}", expect = "【空间】阿绫 现在：茶肆（0 分钟前到，走路）\n这0分钟够去：家(0分)、自家宅院(0分)\n（换地方要交代怎么去的、路上花了多久；来不及去的地方就别凭空出现 —— 可以用 [loc:地名] / [loc:地名|骑车] 标注她到了哪，[ploc:地名] 标你到哪；标注不会显示给玩家。）"),
        SpaceInjectCase(label = "关掉空间层", roleName = "阿绫",
                       worldJson = "",
                       stateJson = "",
                       roles = listOf("user"), stamps = listOf("2026-05-04T12:00:00"),
                       scale = 1.0, nowIso = "2026-05-04T12:00:00",
                       cfgJson = "{\"enabled\": false, \"max_chars\": 240, \"show_reachable\": true, \"reachable_limit\": 4, \"default_transport\": \"走路\", \"warn_when_impossible\": true, \"state_dir\": \"space\"}", expect = ""),
        SpaceInjectCase(label = "预算很小要截断", roleName = "阿绫",
                       worldJson = "{\"name\": \"校园日常\", \"description\": \"六月，栀子花开\", \"params\": {\"space\": \"{\\\"places\\\": [{\\\"name\\\": \\\"教学楼\\\", \\\"minutes\\\": 6}, {\\\"name\\\": \\\"食堂\\\", \\\"minutes\\\": 8, \\\"open\\\": [6, 20]}, {\\\"name\\\": \\\"图书馆\\\", \\\"minutes\\\": 10, \\\"open\\\": [8, 22]}, {\\\"name\\\": \\\"便利店\\\", \\\"minutes\\\": 5, \\\"open\\\": [22, 2]}], \\\"home\\\": \\\"宿舍\\\", \\\"rooms\\\": [\\\"卧室\\\", \\\"阳台\\\"], \\\"transport\\\": {\\\"走路\\\": 1.0, \\\"骑车\\\": 0.4}, \\\"links\\\": {\\\"教学楼|图书馆\\\": 3}}\"}}",
                       stateJson = "",
                       roles = listOf("user"), stamps = listOf("2026-05-04T12:00:00"),
                       scale = 1.0, nowIso = "2026-05-04T12:00:00",
                       cfgJson = "{\"enabled\": true, \"max_chars\": 100, \"show_reachable\": true, \"reachable_limit\": 4, \"default_transport\": \"走路\", \"warn_when_impossible\": true, \"state_dir\": \"space\"}", expect = "【空…\n（换地方要交代怎么去的、路上花了多久；来不及去的地方就别凭空出现 —— 可以用 [loc:地名] / [loc:地名|骑车] 标注她到了哪，[ploc:地名] 标你到哪；标注不会显示给玩家。）"),
        SpaceInjectCase(label = "720× 时间", roleName = "阿绫",
                       worldJson = "",
                       stateJson = "{\"place\": \"家\", \"since\": \"2026-05-04T12:00:00\", \"by\": \"走路\"}",
                       roles = listOf("user"), stamps = listOf("2026-05-04T12:00:00"),
                       scale = 720.0, nowIso = "2026-05-04T12:00:00",
                       cfgJson = "{\"enabled\": true, \"max_chars\": 240, \"show_reachable\": true, \"reachable_limit\": 4, \"default_transport\": \"走路\", \"warn_when_impossible\": true, \"state_dir\": \"space\"}", expect = "【空间】阿绫 现在：家（0 分钟前到，走路）\n屋里：卧室、客厅、厨房、卫生间、阳台、书房、玄关（都在 1 分钟内）\n（换地方要交代怎么去的、路上花了多久；来不及去的地方就别凭空出现 —— 可以用 [loc:地名] / [loc:地名|骑车] 标注她到了哪，[ploc:地名] 标你到哪；标注不会显示给玩家。）"),
    )
}
